certificates:
  - name: default-cert

  - name: "example-cert"
    subject:
      C: "US"
      ST: "California"
      L: "San Francisco"
      O: "Example Organization"
      OU: "IT Department"
      CN: "example.com"
      emailAddress: "admin@example.com"
    san:
      - "www.example.com"
      - "api.example.com"
    keySize: 2048
    digestAlgorithm: "SHA256"
    validityDays: 90

  - name: "test-cert"
    subject:
      C: "US"
      ST: "New York"
      L: "New York City"
      O: "Test Org"
      CN: "test.com"
    san:
      - "www.test.com"
    keySize: 4096
    digestAlgorithm: "SHA256"
    validityDays: 30
