additional-hosts:
  - localhost
  - 127.0.0.1
  - ::1
certs:
  - name: service1
  - name: my-client
    client: true
  - name: service2
    hosts: 
      - example.com
  - name: service3
    hosts: 
      - www.example.com
      - another.example.com
    pfx: true
    